// This file was generated by Firebase Studio
// and should not be edited manually.

// To change the Firebase project your app is connected to,
// use the 'Change Firebase Project' action in the Toolbar.
import { initializeApp } from 'firebase/app';

const firebaseApp = initializeApp({
  projectId: 'studio-1550949121-a9aca',
  appId: '1:804489168175:web:d9bdc7d31a0ef506450dda',
  apiKey: 'AIzaSyDss9qSFFYqXHW71oaEs7LBxVzmZjfG_xA',
  authDomain: 'studio-1550949121-a9aca.firebaseapp.com',
  measurementId: '',
  messagingSenderId: '804489168175',
});

export const getFirebaseConfig = () => {
  if (!firebaseApp) {
    throw new Error('Firebase app has not been initialized');
  }
  return firebaseApp.options;
};
